/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        bocanada: '#0A192F',
        loriga: '#F0F5F9',
        solstis: '#D4AF37',
        halford: '#C0C0C0',
        folsom: '#050505',
        bunbury: '#990000',
        vegas: '#708090',
        surface: '#141313',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2b2a2a',
        'surface-container-highest': '#353434',
        'surface-dim': '#141313',
        'surface-bright': '#3a3939',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c7',
        'on-background': '#e5e2e1',
        background: '#141313',
        primary: '#c9c6c5',
        'on-primary': '#313030',
        'primary-container': '#050505',
        'on-primary-container': '#797777',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c9c6c5',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474646',
        secondary: '#e9c349',
        'on-secondary': '#3c2f00',
        'secondary-container': '#af8d11',
        'on-secondary-container': '#342800',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        tertiary: '#c6c6c6',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#040505',
        'on-tertiary-container': '#767777',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#464747',
        outline: '#8e9192',
        'outline-variant': '#444748',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#5f5e5e',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      fontFamily: {
        'display': ['Playfair Display', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '900' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        'technical-sm': ['13px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      spacing: {
        'gutter': '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
      }
    }
  },
  plugins: []
}
